import type { TaskRequest, TaskResult, SpeculativeResult, AgentRole, LogFn } from "./types.js";
import type { Cluster } from "./cluster.js";

interface DraftConfig {
  draftRole: AgentRole;
  verifyRole: AgentRole;
  acceptanceThreshold: number;
}

const DEFAULT_DRAFT_CONFIG: DraftConfig = {
  draftRole: "clerk",
  verifyRole: "planner",
  acceptanceThreshold: 0.7,
};

const TASK_DRAFT_CONFIGS: Partial<Record<string, DraftConfig>> = {
  implement: { draftRole: "fixer", verifyRole: "implementer", acceptanceThreshold: 0.6 },
  fix_tsc: { draftRole: "clerk", verifyRole: "fixer", acceptanceThreshold: 0.5 },
  fix_test: { draftRole: "clerk", verifyRole: "fixer", acceptanceThreshold: 0.5 },
};

export class SpeculativeExecutor {
  private cluster: Cluster;
  private log: LogFn;

  constructor(cluster: Cluster, logFn?: LogFn) {
    this.cluster = cluster;
    this.log = logFn || (() => {});
  }

  async draftAndVerify(request: TaskRequest): Promise<SpeculativeResult> {
    const config = TASK_DRAFT_CONFIGS[request.type] || DEFAULT_DRAFT_CONFIG;

    this.log("INFO", `Speculative: draft(${config.draftRole}) → verify(${config.verifyRole}) for ${request.type}`);

    const draftRequest: TaskRequest = {
      ...request,
      role: config.draftRole,
      maxTokens: request.maxTokens ? Math.ceil(request.maxTokens * 1.2) : 4096,
      temperature: 0.3,
    };

    const draftResult = await this.cluster.execute(draftRequest);

    if (!draftResult.success || draftResult.content.length < 50) {
      this.log("WARN", `Draft failed, falling back to direct ${config.verifyRole}`);
      const fallback = await this.cluster.execute({ ...request, role: config.verifyRole });
      this.cluster.getStats().speculativeRejected++;
      return {
        accepted: false, draft: draftResult, verification: fallback,
        final: fallback.success ? fallback.content : "", savedTokens: 0,
      };
    }

    const verifyRequest: TaskRequest = {
      type: "review",
      role: config.verifyRole,
      system: `You are verifying code generated by a smaller model. Review and correct if needed. If the code is correct and complete, return it unchanged. If it has errors, fix them.

Return ONLY the final corrected code. No explanation.`,
      user: `ORIGINAL TASK:\n${request.user}\n\nDRAFT OUTPUT:\n${draftResult.content}`,
      maxTokens: request.maxTokens || 4096,
      temperature: 0.2,
    };

    const verifyResult = await this.cluster.execute(verifyRequest);

    if (!verifyResult.success) {
      this.cluster.getStats().speculativeRejected++;
      return {
        accepted: false, draft: draftResult, verification: verifyResult,
        final: draftResult.content, savedTokens: 0,
      };
    }

    const similarity = this.computeSimilarity(draftResult.content, verifyResult.content);
    const accepted = similarity >= config.acceptanceThreshold;

    if (accepted) {
      this.log("INFO", `Speculative ACCEPTED (similarity=${(similarity * 100).toFixed(0)}%)`);
      this.cluster.getStats().speculativeAccepted++;
      return {
        accepted: true, draft: draftResult, verification: verifyResult,
        final: draftResult.content,
        savedTokens: (verifyResult.tokensIn || 0) + (verifyResult.tokensOut || 0),
      };
    }

    this.log("INFO", `Speculative REJECTED (similarity=${(similarity * 100).toFixed(0)}%), using verification`);
    this.cluster.getStats().speculativeRejected++;
    return {
      accepted: false, draft: draftResult, verification: verifyResult,
      final: verifyResult.content,
      savedTokens: (draftResult.tokensOut || 0) - (verifyResult.tokensOut || 0),
    };
  }

  async multiDraft(request: TaskRequest, draftCount: number): Promise<SpeculativeResult> {
    const config = TASK_DRAFT_CONFIGS[request.type] || DEFAULT_DRAFT_CONFIG;
    const draftSlots = this.cluster.getSlotsByRole(config.draftRole);
    const count = Math.min(draftCount, draftSlots.length, 3);

    if (count < 2) {
      return this.draftAndVerify(request);
    }

    this.log("INFO", `Multi-draft: ${count} drafts → verify for ${request.type}`);

    const draftRequests = Array.from({ length: count }, (_, i) => ({
      ...request,
      role: config.draftRole,
      temperature: 0.3 + i * 0.15,
    }));

    const drafts = await this.cluster.executeParallel(draftRequests);
    const validDrafts = drafts.filter((d: TaskResult) => d.success && d.content.length > 50);

    if (validDrafts.length === 0) {
      const fallback = await this.cluster.execute({ ...request, role: config.verifyRole });
      return { accepted: false, draft: drafts[0], verification: fallback, final: fallback.success ? fallback.content : "", savedTokens: 0 };
    }

    const bestDraft = validDrafts.sort((a: TaskResult, b: TaskResult) => b.content.length - a.content.length)[0];

    const verifyRequest: TaskRequest = {
      type: "review",
      role: config.verifyRole,
      system: "You are a senior code reviewer. Review the following drafts and return the BEST version, or synthesize a better one. Return ONLY code, no explanation.",
      user: `TASK: ${request.user}\n\n${validDrafts.map((d: TaskResult, i: number) => `DRAFT ${i + 1}:\n${d.content.slice(0, 2000)}`).join("\n\n---\n\n")}`,
      maxTokens: request.maxTokens || 4096,
      temperature: 0.2,
    };

    const verifyResult = await this.cluster.execute(verifyRequest);

    if (!verifyResult.success || verifyResult.content.length < 50) {
      this.cluster.getStats().speculativeAccepted++;
      return { accepted: true, draft: bestDraft, verification: verifyResult, final: bestDraft.content, savedTokens: 0 };
    }

    this.cluster.getStats().speculativeAccepted++;
    return { accepted: true, draft: bestDraft, verification: verifyResult, final: verifyResult.content, savedTokens: 0 };
  }

  private computeSimilarity(a: string, b: string): number {
    const aWords = new Set(a.toLowerCase().split(/\s+/));
    const bWords = new Set(b.toLowerCase().split(/\s+/));
    const intersection = [...aWords].filter(w => bWords.has(w)).length;
    const union = new Set([...aWords, ...bWords]).size;
    return union > 0 ? intersection / union : 0;
  }
}
